### PR TITLE
grammatical tweaks in README.md

### PR DESCRIPTION
**Pull request by brandondrew**
I noticed a few grammatical issues in the early part of the README, so I went through about the first 150 lines and made as many improvements as I could.

But at line 147 I ran into an issue I can't fix without asking a question.  I think maybe a word is missing, and I can't guess what it is.

> Using the middleware is optional, as the JavaScript snippet already for AJAX requests on the client.

What does the JavaScript snippet already do?

If you agree that these are improvements and would like me to continue on the rest of the README, just let me know.  And if you can tell me what the sentence above was supposed to say, I'll do my best to make it as clear as possible using standard English syntax.

### CODE REVIEW

**Comment by KD6-3** [comment]
> capybara-lockstep requires a JavaScript snippet to be embedded by the application under test. If that snippet is missing on a screen, capybara-lockstep will not be able to **synchronize** with the browser. In that case the test will continue without synchronization.

I think the word you are looking for is **synchronize**.

**Comment by brandondrew** [comment]
@KD6-3 yes that makes sense.  I think you're right.

**Review by triskweline — APPROVED** [review]

**Comment by triskweline** [comment]
Thanks for doing this @brandondrew.

Regarding the sentence that was missing a verb, I changed that to:

> Using the middleware is optional, as the [JavaScript snippet](#including-the-javascript-snippet-required) already waits for asynchronous work on the client

**Comment by brandondrew** [comment]
@triskweline you're very welcome!

**Pull request merged**
